#!/usr/bin/env perl
######################################################################
# friendly-router database frontend.
#
# --------------------------------------------------------------------
#
# this script need:
#   - YAML (required for database management)
#   - JSON (required only for JSON converter)
#   - dbi (required only for SQL converter)
#
# --------------------------------------------------------------------
#
# future usage description:
#   friendly-router [create|update|delete] \
#                   [product|reseller|manufacturer|os] \
#                   --name Name [--extra-options]
#   friendly-router validate yaml
#   friendly-router generate sql
#   friendly-router generate json
#
######################################################################

use strict;
use warnings;

my $opts = { debug => 1 };

######################################################################
# log package, share accross all object, contain default logging
# function.
######################################################################
{ package _log;
  use strict;
  use warnings;

  sub debug {
      if ($opts->{debug}) {
	  my $self = shift();
	  my $string = shift();
	  printf(STDERR "debug: %s " . $string . "\n", $self, @_);
      }
  }
  
  1; }

######################################################################
# _wrapper package make easy hard things and defined lot for playing
# with perl datastructure
######################################################################
{ package _wrapper;
  use strict;
  use warnings;
  use YAML;
  use parent -norequire, "_log";

  # simple constructor
  sub new {
      my $class = shift();
      my $self = { @_ };
      bless($self, $class);
      return $self->init();
  }

  sub set_template {
      my $self = shift();
      my $template = shift();
      $self->{template_file} = $template;
      return $self;
  }

  sub get_template {
      my $self = shift();
      return $self->{template_file};
  }
  
  sub load_template {
      my $self = shift();
      
      if (-f $self->{template_file}) {
	  open(my $fd, "<", $self->{template_file});
	  my $yaml = join("", <$fd>);
	  close($fd);
	  my $data = Load($yaml);
	  $self->{template} = $data;
      }
      return $self;
  }

  sub print_template {
      my $self = shift();
      my $data = $self->{template};
      _fsm->new(\$data)->parse();
  }

  1; }

######################################################################
#
######################################################################
{ package _os;
  use parent -norequire, "_wrapper";
  
  sub init {
      my $self = shift();
      $self->set_template("./yaml/os.template");
      return $self;
  }
  
  1; }


######################################################################
#
######################################################################
{ package _product;
  use parent -norequire, "_wrapper";
  
  sub init {
      my $self = shift();
      $self->set_template("./yaml/product.template");
      return $self;
  }

  1; }

######################################################################
#
######################################################################
{ package _reseller;
  use parent -norequire, "_wrapper";
  
  sub init {
      my $self = shift();
      $self->set_template("./yaml/reseller.template");
      return $self;
  }

  1; }

######################################################################
#
######################################################################
{ package _manufacturer;
  use parent -norequire, "_wrapper";
  
  sub init {
      my $self = shift();
      $self->set_template("./yaml/manufacturer.template");
      return $self;
  }

  1; }

######################################################################
#
######################################################################
{ package _database;
  use strict;
  use warnings;
  use YAML;
    
  1; }

######################################################################
#
######################################################################
{ package _fsm;
  use strict;
  use warnings;
  use parent -norequire, "_log";

  # constructor
  sub new {
      my $class = shift();
      my $origin = shift();
      my $callback = shift();
      my $self = { };
      bless($self, $class);
      return $self->set_data($origin)->set_callback($callback);
  }

  # set data as origin.
  sub set_data {
      my $self = shift();
      my $data = shift() || 0;
      $self->{origin} = $data;
      return $self;
  }

  # set callback called before routing
  sub set_callback {
      my $self = shift();
      my $callback = shift() || 0;
      $self->{callback} = $callback;
      return $self;
  }

  # callback validation
  sub callback {
      my $self = shift();
      my $callback = $self->{callback};
      if ($callback) {
	  return &$callback(@_);
      }
      return ();
  }

  # main parse function
  sub parse {
      my $self = shift();
      my $data = shift() || $self->{origin} or
	  die("no datastructure set.");
      
      my $ret = $self->router($data, @_);
      return $self;
  }

  # router function based on reference
  sub router {
      my $self = shift();
      my $data = shift();
      my $ref = ref($data) || "LEAF";
      
      return $self->$ref($data, @_);
  }

  sub SCALAR {
      my $self = shift();
      my $data = shift();
      
      $self->debug("scalar: %s", $data);
      $self->router($$data, @_);
  }
  
  sub HASH {
      my $self = shift();
      my $data = shift();

      my @keys = keys(%$data);
      foreach my $key (@keys) {
	  my $value = $data->{$key};
	  $self->debug("hash: %s -> %s", $key, $value);
	  $self->callback("HASH", $data, $key);
	  $self->router($value, @_);
      }
  }
  
  sub ARRAY {
      my $self = shift();
      my $data = shift();
      
      foreach my $item (@$data) {
	  $self->callback("ARRAY", $data, $item);
	  $self->router($item, @_);
      }
  }
  
  sub REF {
      my $self = shift();
      my $data = shift();
      
      $self->debug("ref: %s", $data);
      $self->router($$data, @_);
  }
  
  sub CODE {
      my $self = shift();
      my $data = $self;
      
      $self->debug("code: %s", $data);
  }
  
  sub GLOB {
      my $self = shift();
      my $data = shift();
      
      $self->debug("glob: %s", <$data>);
      $self->router(<$data>, @_);
  }

  sub LEAF {
      my $self = shift();
      $self->callback("LEAF", @_);
      return @_;
  }
    
  1; }

######################################################################
#
######################################################################
{ package _usage;
  
  1; }

######################################################################
#
######################################################################
{ package main;
  use strict;
  use warnings;
  use YAML;

  sub return_keys {
      return keys(%$_);
  }
  
  open(my $fd, "<", "./yaml/product/alix1e.yaml");
  my $yaml = join("", <$fd>);
  my @data = Load($yaml);
  my $fsm = _fsm->new(\@data,
		      sub {
			  my $ref = shift();
			  my $data = shift();
			  printf("callback %s, %s\n", $ref, $data);
			  return $data, @_;
		      }
      )->parse();
  close($fd);  
  
  1; }
